### ISSUE TITLE
Soulbound Tokens Smart Contract

### ISSUE THREAD

**Issue by Hemang28** [atom-dao/Learnweb3#20]
Submit your smart contract here

**Comment by Skandesh** [comment]
### Here's my submission for the contest ### 
**Contract code -** 

```
/*
************** ATOM DAO **************
- Only selected 255 members have the ability to vote for governace (used 'uint8' for tokenId)
- Governors will be issued a Soul-bound token, which is non-transferrable NFT's
- Creator of ATOM DAO, issues these NFT's.
- If any misbehavior from any governors, owner can revoke/cancel their membership
- Person who has membership can burn the tokens
- Every 2 years the membership for ATOM DAO will be refreshed and only well-performing members would get another opportunity in the next tenure.

*/

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "@openzeppelin/contracts@4.7.3/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts@4.7.3/access/Ownable.sol";
import "@openzeppelin/contracts@4.7.3/utils/Counters.sol";

contract ATOMDAO is ERC721, Ownable {
    using Counters for Counters.Counter;

    Counters.Counter private _tokenIdCounter;

    event Attest(address indexed to, uint8 indexed tokenId);
    event Revoke(address indexed to, uint8 indexed tokenId);

    constructor() ERC721("ATOM DAO", "ATOM") {}

    ///  issues the metadata for the ATOM DAO image 

    function _baseURI() internal pure override returns (string memory) {
        return "https://ipfs.io/ipfs/QmRCKD91mg4XsxvbhMn8V3cUBr92RaSZiFBsm7DimDioa8";
    }

    /// @dev issues the NFT to the members, this is done only by the owner using the onlyOwner modifier
    /// @param to address of the member getting membership from the DAO

    function safeMint(address to) public onlyOwner {
        uint256 tokenId = _tokenIdCounter.current();
        _tokenIdCounter.increment();
        _safeMint(to, tokenId);
    }

    ///@dev this burns the ownership of the NFT either by the tokenholder or the owner
    ///@param tokenId ID of that particular NFT
    function burn(uint8 tokenId) external  {
        require(ownerOf(tokenId) == msg.sender, "Owner of this token can only burn it!");
        _burn(tokenId);
    }
    ///@dev revokes the membership of DAO if any misconduct or tenure expiration
    function revoke(uint256 tokenId) external onlyOwner {
        _burn(tokenId);
    }


    //Overriding the internal function from the ERC721 to restrict transfer of NFT's to other accounts 
    function _beforeTokenTransfer(address from, address to, uint8 ) pure override internal {
        require(from == address(0) || to == address(0), "This is a special token which can't be transferred");
    } 

    //Overriding the internal function from the ERC721 to restrict transfer of NFT's to other accounts 
    //Emitting the respective events for revoking or giving membership access
    function _afterTransfer(address from, address to, uint8 tokenId)  override internal {
        if (from == address(0)){
            emit Attest( to, tokenId);
        }
        else if (to == address(0)){
            emit Revoke(to, tokenId);
        }
    } 


    
    ///@dev this burns the ownership of the NFT either by the tokenholder or the owner
    ///@param tokenId ID of that particular NFT
    function _burn(uint256 tokenId) internal override(ERC721){
        super._burn(tokenId);
    }
}



```




Comments and suggestions on this are encouraged. 

(This is my first bounty submission :))

**Comment by LokeshRM** [comment]
## Smart Contract

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;

/* These Soulbound smart contract represents the NFTs which are certificates of
   an degree for students passed out from college.
   The owner(college) of the contract need to issue an certificate for a student so that 
   the student can claim the certificate only once and not transferable
 */
import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

contract SoulBoundNFT is ERC721, ERC721URIStorage, Ownable {
    //  counters used to track the number of ids and issuing ERC721 ids
    using Counters for Counters.Counter;
    Counters.Counter private _tokenIdCounter;

    // cerificates var maps between student address and the tokenURI that contains metadata
    mapping(address => string) public certificates;

    // issuedCerrtificates var maps student address and the status of the certificate issued
    mapping(address => bool) public issuedCertificate;

    constructor() ERC721("SoulDegree", "SDG") {}

    /* @dev checks whether certificate issued or not
       @param _studentAddress is the address to check whether certificate issued or not
     */
    function checkCertificateissued(address _studentAddress)
        public
        view
        returns (bool)
    {
        return issuedCertificate[_studentAddress];
    }

    // @dev issues certificate to a address mentioned by the owner only
    function issueCertificate(address _to) public onlyOwner {
        issuedCertificate[_to] = true;
    }

    /* @dev student claims certificate by minting NFT
       @param _tokenUri is the url to the metadata of the NFT
     */
    function claimCertificate(string memory _tokenUri) public {
        require(
            checkCertificateissued(msg.sender),
            "certificate is not issued or claimed"
        );
        issuedCertificate[msg.sender] = false;
        uint256 _tokenId = _tokenIdCounter.current();
        _tokenIdCounter.increment();
        _safeMint(msg.sender, _tokenId);
        _setTokenURI(_tokenId, _tokenUri);
        certificates[msg.sender] = _tokenUri;
    }

    /* @dev mints NFT directly to the student only by the owner
       @param _to is the address of the student to be minted
       @param _uri is the url of metadata associated with the specific student
     */
    function safeMint(address _to, string memory _uri) public onlyOwner {
        uint256 _tokenId = _tokenIdCounter.current();
        _tokenIdCounter.increment();
        _safeMint(_to, _tokenId);
        _setTokenURI(_tokenId, _uri);
    }

    /* @dev burns the NFT owned by owner , only owner can be allowed to burn token
       @param _tokenId is the id of the token to be burn
     */
    function burn(uint256 _tokenId) public {
        address owner = ERC721.ownerOf(_tokenId);
        require(owner == msg.sender, "Only Owner can burn token");
        _burn(_tokenId);
    }

    /* @dev revokes the NFT issued to someone by owner of the contract
       @param _tokenId is the id of the token to be revoked
     */
    function revokeToken(uint256 _tokenId) public onlyOwner {
        _burn(_tokenId);
    }

    /* @dev checks if @param from is set to zero, if yes then NFT will be transfered to new owner  
       if No then the transaction to be minted is stopped so that the NFT will become
       non-transferable
     */
    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 _tokenId
    ) internal virtual override {
        // checks if the revoke is happening which is done by owner
        if(msg.sender != owner()){
        require(from == address(0), "token transfer is blocked");
        }
        super._beforeTokenTransfer(from, to, _tokenId);
    }

    // _burn and tokenURI are overridden from the parent contracts
    function _burn(uint256 _tokenId)
        internal
        override(ERC721, ERC721URIStorage)
    {
        super._burn(_tokenId);
    }

    function tokenURI(uint256 _tokenId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (string memory)
    {
        return super.tokenURI(_tokenId);
    }
}
```

**Comment by ArpitaGanatra** [comment]
**SoulBound Token Contract**

```// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

//importing required libraries
import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

contract SoulBoundToken is ERC721, ERC721URIStorage, Ownable {
    //using counter to increament the tokenId
    using Counters for Counters.Counter;
    Counters.Counter private _tokenIdCounter;

    // Events to log minting and burning ERC721 token data
    event Minting(address indexed to, uint256 indexed tokenId);
    event Revoke(address indexed to, uint256 indexed tokenId);

    constructor() ERC721("ATOMSOULBOUND", "ATOMSBT") {}

    /**
     * @dev - to mint the ERC721 token
     * @params 
     * to - address of ERC721 token reciepient
     * uri - metadata of the token in the IPFS url
     */
    function safeMint(address to, string memory uri) public onlyOwner {
        uint256 tokenId = _tokenIdCounter.current();
        _tokenIdCounter.increment();
        _safeMint(to, tokenId);
        _setTokenURI(tokenId, uri);
    }

    // The following functions are overrides required by Solidity.
     /**
     * @dev - helper function to burn the ERC721 token by the given tokenId
     */
    function _burn(uint256 tokenId) internal override(ERC721, ERC721URIStorage) {
        super._burn(tokenId);
    }

     /**
     * @dev - to revoke the rights of ERC721 token
     * @params 
     * tokenId - id of the token to be revoked
     */
    function revoke(uint256 tokenId) external {
        address _owner = owner();
        require(ownerOf(tokenId) == msg.sender || _owner == msg.sender , "Only owner of the token can burn it");
        _burn(tokenId);
    }

    /**
     * @dev Hook that is called before any token transfer. This includes minting
     * and burning.
     *
     * Calling conditions:
     *
     * - When `from` and `to` are both non-zero, ``from``'s `tokenId` will be
     * transferred to `to`. (Not applicable in this case)
     * - When `from` is zero, `tokenId` will be minted for `to`.
     * - When `to` is zero, ``from``'s `tokenId` will be burned.
     * - `from` and `to` are never both zero.
     *
     */
    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 tokenId
    ) internal override virtual {
        require(from == address(0) || to == address(0), "SoulBound Tokens are non-transferrable");
    }

    /**
     * @dev Hook that is called after any transfer of tokens. This includes
     * minting and burning.
     *
     * Calling conditions:
     *
     * - when `from` and `to` are both non-zero.(Not Applicable in this case)
     * - `from` and `to` are never both zero.
     *
     */
    function _afterTokenTransfer(
        address from,
        address to,
        uint256 tokenId
    ) internal override virtual {
        if (from == address(0)) {
            emit Minting(to, tokenId);
        }
        else if(to == address(0)) {
            emit Revoke(to, tokenId);
        }
    }

   /**
     * @dev returns the tokenURI associated with particular tokenId
     * @params-
     * - tokenId - id of token
     */
    function tokenURI(uint256 tokenId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (string memory)
    {
        return super.tokenURI(tokenId);
    }
}

**Comment by Hemang28** [comment]
> ### Here's my submission for the contest
> **Contract code -**
> 
> ```
> /*
> ************** ATOM DAO **************
> - Only selected 255 members have the ability to vote for governace (used 'uint8' for tokenId)
> - Governors will be issued a Soul-bound token, which is non-transferrable NFT's
> - Creator of ATOM DAO, issues these NFT's.
> - If any misbehavior from any governors, owner can revoke/cancel their membership
> - Person who has membership can burn the tokens
> - Every 2 years the membership for ATOM DAO will be refreshed and only well-performing members would get another opportunity in the next tenure.
> 
> */
> 
> // SPDX-License-Identifier: MIT
> pragma solidity ^0.8.4;
> 
> import "@openzeppelin/contracts@4.7.3/token/ERC721/ERC721.sol";
> import "@openzeppelin/contracts@4.7.3/access/Ownable.sol";
> import "@openzeppelin/contracts@4.7.3/utils/Counters.sol";
> 
> contract ATOMDAO is ERC721, Ownable {
>     using Counters for Counters.Counter;
> 
>     Counters.Counter private _tokenIdCounter;
> 
>     event Attest(address indexed to, uint8 indexed tokenId);
>     event Revoke(address indexed to, uint8 indexed tokenId);
> 
>     constructor() ERC721("ATOM DAO", "ATOM") {}
> 
>     ///  issues the metadata for the ATOM DAO image 
> 
>     function _baseURI() internal pure override returns (string memory) {
>         return "https://ipfs.io/ipfs/QmRCKD91mg4XsxvbhMn8V3cUBr92RaSZiFBsm7DimDioa8";
>     }
> 
>     /// @dev issues the NFT to the members, this is done only by the owner using the onlyOwner modifier
>     /// @param to address of the member getting membership from the DAO
> 
>     function safeMint(address to) public onlyOwner {
>         uint256 tokenId = _tokenIdCounter.current();
>         _tokenIdCounter.increment();
>         _safeMint(to, tokenId);
>     }
> 
>     ///@dev this burns the ownership of the NFT either by the tokenholder or the owner
>     ///@param tokenId ID of that particular NFT
>     function burn(uint8 tokenId) external  {
>         require(ownerOf(tokenId) == msg.sender, "Owner of this token can only burn it!");
>         _burn(tokenId);
>     }
>     ///@dev revokes the membership of DAO if any misconduct or tenure expiration
>     function revoke(uint256 tokenId) external onlyOwner {
>         _burn(tokenId);
>     }
> 
> 
>     //Overriding the internal function from the ERC721 to restrict transfer of NFT's to other accounts 
>     function _beforeTokenTransfer(address from, address to, uint8 ) pure override internal {
>         require(from == address(0) || to == address(0), "This is a special token which can't be transferred");
>     } 
> 
>     //Overriding the internal function from the ERC721 to restrict transfer of NFT's to other accounts 
>     //Emitting the respective events for revoking or giving membership access
>     function _afterTransfer(address from, address to, uint8 tokenId)  override internal {
>         if (from == address(0)){
>             emit Attest( to, tokenId);
>         }
>         else if (to == address(0)){
>             emit Revoke(to, tokenId);
>         }
>     } 
> 
> 
>     
>     ///@dev this burns the ownership of the NFT either by the tokenholder or the owner
>     ///@param tokenId ID of that particular NFT
>     function _burn(uint256 tokenId) internal override(ERC721){
>         super._burn(tokenId);
>     }
> }
> ```
> 
> Comments and suggestions on this are encouraged.
> 
> (This is my first bounty submission :))

Can you tell your discord name please

**Comment by Hemang28** [comment]
> ## Smart Contract
> ```
> // SPDX-License-Identifier: MIT
> pragma solidity ^0.8.7;
> 
> /* These Soulbound smart contract represents the NFTs which are certificates of
>    an degree for students passed out from college.
>    The owner(college) of the contract need to issue an certificate for a student so that 
>    the student can claim the certificate only once and not transferable
>  */
> import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
> import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
> import "@openzeppelin/contracts/access/Ownable.sol";
> import "@openzeppelin/contracts/utils/Counters.sol";
> 
> contract SoulBoundNFT is ERC721, ERC721URIStorage, Ownable {
>     //  counters used to track the number of ids and issuing ERC721 ids
>     using Counters for Counters.Counter;
>     Counters.Counter private _tokenIdCounter;
> 
>     // cerificates var maps between student address and the tokenURI that contains metadata
>     mapping(address => string) public certificates;
> 
>     // issuedCerrtificates var maps student address and the status of the certificate issued
>     mapping(address => bool) public issuedCertificate;
> 
>     constructor() ERC721("SoulDegree", "SDG") {}
> 
>     /* @dev checks whether certificate issued or not
>        @param _studentAddress is the address to check whether certificate issued or not
>      */
>     function checkCertificateissued(address _studentAddress)
>         public
>         view
>         returns (bool)
>     {
>         return issuedCertificate[_studentAddress];
>     }
> 
>     // @dev issues certificate to a address mentioned by the owner only
>     function issueCertificate(address _to) public onlyOwner {
>         issuedCertificate[_to] = true;
>     }
> 
>     /* @dev student claims certificate by minting NFT
>        @param _tokenUri is the url to the metadata of the NFT
>      */
>     function claimCertificate(string memory _tokenUri) public {
>         require(
>             checkCertificateissued(msg.sender),
>             "certificate is not issued or claimed"
>         );
>         issuedCertificate[msg.sender] = false;
>         uint256 _tokenId = _tokenIdCounter.current();
>         _tokenIdCounter.increment();
>         _safeMint(msg.sender, _tokenId);
>         _setTokenURI(_tokenId, _tokenUri);
>         certificates[msg.sender] = _tokenUri;
>     }
> 
>     /* @dev mints NFT directly to the student only by the owner
>        @param _to is the address of the student to be minted
>        @param _uri is the url of metadata associated with the specific student
>      */
>     function safeMint(address _to, string memory _uri) public onlyOwner {
>         uint256 _tokenId = _tokenIdCounter.current();
>         _tokenIdCounter.increment();
>         _safeMint(_to, _tokenId);
>         _setTokenURI(_tokenId, _uri);
>     }
> 
>     /* @dev burns the NFT owned by owner , only owner can be allowed to burn token
>        @param _tokenId is the id of the token to be burn
>      */
>     function burn(uint256 _tokenId) public {
>         address owner = ERC721.ownerOf(_tokenId);
>         require(owner == msg.sender, "Only Owner can burn token");
>         _burn(_tokenId);
>     }
> 
>     /* @dev revokes the NFT issued to someone by owner of the contract
>        @param _tokenId is the id of the token to be revoked
>      */
>     function revokeToken(uint256 _tokenId) public onlyOwner {
>         _burn(_tokenId);
>     }
> 
>     /* @dev checks if @param from is set to zero, if yes then NFT will be transfered to new owner  
>        if No then the transaction to be minted is stopped so that the NFT will become
>        non-transferable
>      */
>     function _beforeTokenTransfer(
>         address from,
>         address to,
>         uint256 _tokenId
>     ) internal virtual override {
>         // checks if the revoke is happening which is done by owner
>         if(msg.sender != owner()){
>         require(from == address(0), "token transfer is blocked");
>         }
>         super._beforeTokenTransfer(from, to, _tokenId);
>     }
> 
>     // _burn and tokenURI are overridden from the parent contracts
>     function _burn(uint256 _tokenId)
>         internal
>         override(ERC721, ERC721URIStorage)
>     {
>         super._burn(_tokenId);
>     }
> 
>     function tokenURI(uint256 _tokenId)
>         public
>         view
>         override(ERC721, ERC721URIStorage)
>         returns (string memory)
>     {
>         return super.tokenURI(_tokenId);
>     }
> }
> ```

Please provide me your discord name
