### ISSUE TITLE
Auction Smart Contract

### ISSUE THREAD

**Issue by Hemang28** [atom-dao/Learnweb3#6]
Refer given link more info [https://github.com/atom-dao/Learnweb3](url) and go to Auction Smart Contract.md

Cash Bounty for this task is Rs.1000 (INR)

**Comment by coder-rancho** [comment]
Should I make a new folder for this smart contract and new branch or whatever?

**Comment by Hemang28** [comment]
> Should I make a new folder for this smart contract and new branch or whatever?

u can pull request it or u can submit here

**Comment by coder-rancho** [comment]
I've made a pull request
